### ISSUE TITLE
Unexpected error fetching IPMI resource status data: 'debug'

### ISSUE THREAD

**Issue by chunkster29** [ateodorescu/home-assistant-ipmi#12]
This error originated from a custom integration.

Logger: custom_components.ipmi
Source: custom_components/ipmi/__init__.py:352
Integration: IPMI connector (documentation, issues)
First occurred: 16:42:37 (30 occurrences)
Last logged: 16:56:14

Unexpected error fetching IPMI resource status data: 'debug'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ipmi/__init__.py", line 91, in async_update_data
    await hass.async_add_executor_job(data.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ipmi/__init__.py", line 352, in update
    if (json["debug"] is not None):
        ~~~~^^^^^^^^^
KeyError: 'debug'

**Comment by chunkster29** [comment]
removing the two lines fixes it

**Comment by ateodorescu** [comment]
I'm sorry about this. I'm not a Python expert and didn't know how to test if a json key is defined or not. Apparently that's not the way to do it. I have removed those lines because it does not make sense to log the debug info that the addon sends. The addon does that already in its log file.
