### ISSUE TITLE
migration error after update

### ISSUE THREAD

**Issue by markusschloesser** [ateodorescu/home-assistant-ipmi#31]
Hi, I updated both add-on and intergration. Unfortunately the integration throws

```Logger: homeassistant.config_entries
Source: config_entries.py:701
First occurred: 17:43:03 (1 occurrences)
Last logged: 17:43:03

Error migrating entry server@192.168.222.43:623 for ipmi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 701, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ipmi/__init__.py", line 183, in async_migrate_entry
    hass.config_entries.async_update_entry(config_entry, data=new, minor_version=3, version=1)
TypeError: ConfigEntries.async_update_entry() got an unexpected keyword argument 'minor_version'
```

The add-on works fine 
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: IPMItool server
 IPMItool server
-----------------------------------------------------------
 Add-on version: 1.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.1  (amd64 / qemux86-64)
 Home Assistant Core: 2024.2.5
 Home Assistant Supervisor: 2024.03.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
[17:40:55] INFO: Starting PHP-FPM...
[17:40:56] INFO: Starting NGinx...
```

**Comment by markusschloesser** [comment]
either the 5th reboot or the installation of the march update of HA fixed this issue! :-)
Also I now see the power consumption, so 👍😊
