### ISSUE TITLE
Unexpected error when trying to add server again

### ISSUE THREAD

**Issue by kimsvane** [ateodorescu/home-assistant-ipmi#44]
Hi 

Im trying to reset the tool to get values back. 
But now im not able to connect to IPMI-server, during setup of the Device it just states: Unexpected error 

```
Unexpected exception: Detected that custom integration 'ipmi' calls async_dispatcher_send from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_dispatcher_send at custom_components/ipmi/server.py, line 299: async_dispatcher_send(. Please report it to the author of the 'ipmi' custom integration.
Traceback (most recent call last):
  File "/config/custom_components/ipmi/config_flow.py", line 159, in _async_validate_or_error
    info = await validate_input(self.hass, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ipmi/config_flow.py", line 81, in validate_input
    await hass.async_add_executor_job(ipmi_data.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ipmi/server.py", line 299, in update
    async_dispatcher_send(
  File "/usr/src/homeassistant/homeassistant/helpers/dispatcher.py", line 214, in async_dispatcher_send
    hass.verify_event_loop_thread("async_dispatcher_send")
  File "/usr/src/homeassistant/homeassistant/core.py", line 447, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'ipmi' calls async_dispatcher_send from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_dispatcher_send at custom_components/ipmi/server.py, line 299: async_dispatcher_send(. Please report it to the author of the 'ipmi' custom integration.

```

**Comment by ateodorescu** [comment]
What's the `ipmi` integration version that you have installed? Maybe you should install the latest one.

**Comment by kimsvane** [comment]
So embarrassing, I forgot I did the manual install. It works now after installing from HACS.
